### ISSUE TITLE
Error with RoseGarden

### ISSUE THREAD

**Issue by NoltoxGit** [Oribuin/EternalTags#38]
Hello,
I've updated EternalTags to the latest version available on spigotmc, and i've this error when the server start and when i reload the plugin:
```log
[13:18:56 INFO]: [EternalTags] Enabling EternalTags v1.3.0
[13:18:56 INFO]: [EternalTags] Data handler connected using SQLite.
[13:18:56 WARN]: xyz.oribuin.eternaltags.libs.rosegarden.manager.AbstractLocaleManager$LocaleException: Missing locale string: command-tags-description
[13:18:56 WARN]: at EternalTags-1.3.0.jar//xyz.oribuin.eternaltags.libs.rosegarden.manager.AbstractLocaleManager.getErrorMessage(AbstractLocaleManager.java:362)
[13:18:56 WARN]: at EternalTags-1.3.0.jar//xyz.oribuin.eternaltags.libs.rosegarden.manager.AbstractLocaleManager.getCommandLocaleMessage(AbstractLocaleManager.java:223)
[13:18:56 WARN]: at EternalTags-1.3.0.jar//xyz.oribuin.eternaltags.libs.rosegarden.manager.AbstractLocaleManager.getCommandLocaleMessage(AbstractLocaleManager.java:206)
[13:18:56 WARN]: at EternalTags-1.3.0.jar//xyz.oribuin.eternaltags.libs.rosegarden.command.framework.RoseCommandWrapper.register(RoseCommandWrapper.java:108)
[13:18:56 WARN]: at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
[13:18:56 WARN]: at EternalTags-1.3.0.jar//xyz.oribuin.eternaltags.libs.rosegarden.manager.AbstractCommandManager.reload(AbstractCommandManager.java:31)
[13:18:56 WARN]: at EternalTags-1.3.0.jar//xyz.oribuin.eternaltags.libs.rosegarden.RosePlugin.getManager(RosePlugin.java:222)
[13:18:56 WARN]: at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
[13:18:56 WARN]: at EternalTags-1.3.0.jar//xyz.oribuin.eternaltags.libs.rosegarden.RosePlugin.reload(RosePlugin.java:182)
[13:18:56 WARN]: at EternalTags-1.3.0.jar//xyz.oribuin.eternaltags.EternalTags.reload(EternalTags.java:56)
[13:18:56 WARN]: at EternalTags-1.3.0.jar//xyz.oribuin.eternaltags.libs.rosegarden.RosePlugin.onEnable(RosePlugin.java:113)
[13:18:56 WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287)
[13:18:56 WARN]: at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188)
[13:18:56 WARN]: at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[13:18:56 WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[13:18:56 WARN]: at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:653)
[13:18:56 WARN]: at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:564)
[13:18:56 WARN]: at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:675)
[13:18:56 WARN]: at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435)
[13:18:56 WARN]: at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:346)
[13:18:56 WARN]: at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1146)
[13:18:56 WARN]: at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)
[13:18:56 WARN]: at java.base/java.lang.Thread.run(Thread.java:1583)
[13:18:56 INFO]: [PlaceholderAPI] Successfully registered internal expansion: eternaltags [1.3.0]
```
# Logs link: https://mclo.gs/JEkQ9uV

**Comment by NoltoxGit** [comment]
Fixed with the latest update.
