### ISSUE TITLE
Missing locale string: command-tags-description

### ISSUE THREAD

**Issue by sdxqw** [Oribuin/EternalTags#39]
15:19:09 WARN]: xyz.oribuin.eternaltags.libs.rosegarden.manager.AbstractLocaleManager$LocaleException: Missing locale string: command-tags-description
[15:19:09 WARN]: 	at EternalTags-1.3.0-1719542368303.jar//xyz.oribuin.eternaltags.libs.rosegarden.manager.AbstractLocaleManager.getErrorMessage(AbstractLocaleManager.java:362)
[15:19:09 WARN]: 	at EternalTags-1.3.0-1719542368303.jar//xyz.oribuin.eternaltags.libs.rosegarden.manager.AbstractLocaleManager.getCommandLocaleMessage(AbstractLocaleManager.java:223)
[15:19:09 WARN]: 	at EternalTags-1.3.0-1719542368303.jar//xyz.oribuin.eternaltags.libs.rosegarden.manager.AbstractLocaleManager.getCommandLocaleMessage(AbstractLocaleManager.java:206)
[15:19:09 WARN]: 	at EternalTags-1.3.0-1719542368303.jar//xyz.oribuin.eternaltags.libs.rosegarden.command.framework.RoseCommandWrapper.register(RoseCommandWrapper.java:108)
[15:19:09 WARN]: 	at java.base/java.util.ArrayList.forEach(Unknown Source)
[15:19:09 WARN]: 	at EternalTags-1.3.0-1719542368303.jar//xyz.oribuin.eternaltags.libs.rosegarden.manager.AbstractCommandManager.reload(AbstractCommandManager.java:31)
[15:19:09 WARN]: 	at EternalTags-1.3.0-1719542368303.jar//xyz.oribuin.eternaltags.libs.rosegarden.RosePlugin.getManager(RosePlugin.java:222)
[15:19:09 WARN]: 	at java.base/java.util.ArrayList.forEach(Unknown Source)
[15:19:09 WARN]: 	at EternalTags-1.3.0-1719542368303.jar//xyz.oribuin.eternaltags.libs.rosegarden.RosePlugin.reload(RosePlugin.java:182)
[15:19:09 WARN]: 	at EternalTags-1.3.0-1719542368303.jar//xyz.oribuin.eternaltags.EternalTags.reload(EternalTags.java:56)
[15:19:09 WARN]: 	at EternalTags-1.3.0-1719542368303.jar//xyz.oribuin.eternaltags.libs.rosegarden.RosePlugin.onEnable(RosePlugin.java:113)
[15:19:09 WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288)
[15:19:09 WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
[15:19:09 WARN]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
[15:19:09 WARN]: 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
[15:19:09 WARN]: 	at PlugManX-2.4.0.jar//com.rylinaux.plugman.pluginmanager.PaperPluginManager.load(PaperPluginManager.java:403)
[15:19:09 WARN]: 	at PlugManX-2.4.0.jar//com.rylinaux.plugman.pluginmanager.PaperPluginManager.load(PaperPluginManager.java:356)
[15:19:09 WARN]: 	at PlugManX-2.4.0.jar//com.rylinaux.plugman.pluginmanager.PaperPluginManager.reload(PaperPluginManager.java:470)
[15:19:09 WARN]: 	at PlugManX-2.4.0.jar//com.rylinaux.plugman.command.ReloadCommand.execute(ReloadCommand.java:125)
[15:19:09 WARN]: 	at PlugManX-2.4.0.jar//com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:94)
[15:19:09 WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[15:19:09 WARN]: 	at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:91)
[15:19:09 WARN]: 	at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73)
[15:19:09 WARN]: 	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:30)
[15:19:09 WARN]: 	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:13)
[15:19:09 WARN]: 	at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8)
[15:19:09 WARN]: 	at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5)
[15:19:09 WARN]: 	at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103)
[15:19:09 WARN]: 	at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:456)
[15:19:09 WARN]: 	at net.minecraft.commands.Commands.performCommand(Commands.java:363)
[15:19:09 WARN]: 	at net.minecraft.commands.Commands.performCommand(Commands.java:350)
[15:19:09 WARN]: 	at net.minecraft.commands.Commands.performCommand(Commands.java:345)
[15:19:09 WARN]: 	at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2282)
[15:19:09 WARN]: 	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$18(ServerGamePacketListenerImpl.java:2256)
[15:19:09 WARN]: 	at net.minecraft.server.TickTask.run(TickTask.java:18)
[15:19:09 WARN]: 	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151)
[15:19:09 WARN]: 	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
[15:19:09 WARN]: 	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1546)
[15:19:09 WARN]: 	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:195)
[15:19:09 WARN]: 	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125)
[15:19:09 WARN]: 	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1523)
[15:19:09 WARN]: 	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1446)
[15:19:09 WARN]: 	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135)
[15:19:09 WARN]: 	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1412)
[15:19:09 WARN]: 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1273)
[15:19:09 WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326)
[15:19:09 WARN]: 	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by Oribuin** [comment]
This has been fixed already [here](https://github.com/Oribuin/EternalTags/commit/340bf438b453c5c1490a4df686955bf0c393cffc), Please consider updating to 1.3.1, Alternatively you could just add the line `command-tags-description` in your locale file.
