### ISSUE TITLE
tags.yml does not accept comments in 1.1.0

### ISSUE THREAD

**Issue by nhanledev** [Oribuin/EternalTags#7]
If you put any comment into `tags.yml` file (version 1.1.0), the plugin will not load and throw exceptions. The comment stuff worked great in previous version 1.0.12.

Exception log:

```Cannot load configuration from stream
org.bukkit.configuration.InvalidConfigurationException: while parsing a block mapping
 in 'string', line 1, column 1:
    _COMMENT_0: ' note'
    ^
expected <block end>, but found '<block mapping start>'
 in 'string', line 11, column 3:
      gm:
      ^

        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:59) ~[patched_1.17.1.jar:git-Paper-409]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[patched_1.17.1.jar:git-Paper-409]
        at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:217) ~[patched_1.17.1.jar:git-Paper-409]
        at xyz.oribuin.eternaltags.libs.rosegarden.config.CommentedFileConfiguration.reloadConfig(CommentedFileConfiguration.java:52) ~[EternalTags-1.1.0-sgmc.jar:?]
        at xyz.oribuin.eternaltags.manager.TagsManager.loadTags(TagsManager.java:80) ~[EternalTags-1.1.0-sgmc.jar:?]
        at xyz.oribuin.eternaltags.manager.TagsManager.reload(TagsManager.java:67) ~[EternalTags-1.1.0-sgmc.jar:?]
        at java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:647) ~[?:?]
        at xyz.oribuin.eternaltags.libs.rosegarden.RosePlugin.reload(RosePlugin.java:154) ~[EternalTags-1.1.0-sgmc.jar:?]
        at xyz.oribuin.eternaltags.libs.rosegarden.command.command.ReloadCommand.execute(ReloadCommand.java:20) ~[EternalTags-1.1.0-sgmc.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at xyz.oribuin.eternaltags.libs.rosegarden.command.framework.RoseCommandWrapper.executeCommand(RoseCommandWrapper.java:293) ~[EternalTags-1.1.0-sgmc.jar:?]
        at xyz.oribuin.eternaltags.libs.rosegarden.command.framework.RoseCommandWrapper.runCommand(RoseCommandWrapper.java:282) ~[EternalTags-1.1.0-sgmc.jar:?]
        at xyz.oribuin.eternaltags.libs.rosegarden.command.framework.RoseCommandWrapper.execute(RoseCommandWrapper.java:221) ~[EternalTags-1.1.0-sgmc.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.17.1.jar:git-Paper-409]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:869) ~[patched_1.17.1.jar:git-Paper-409]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchServerCommand(CraftServer.java:832) ~[patched_1.17.1.jar:git-Paper-409]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:529) ~[patched_1.17.1.jar:git-Paper-409]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:491) ~[patched_1.17.1.jar:git-Paper-409]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1483) ~[patched_1.17.1.jar:git-Paper-409]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1282) ~[patched_1.17.1.jar:git-Paper-409]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-409]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: org.yaml.snakeyaml.parser.ParserException: while parsing a block mapping
 in 'string', line 1, column 1:
    _COMMENT_0: ' note'
    ^
expected <block end>, but found '<block mapping start>'
 in 'string', line 11, column 3:
      gm:
      ^

        at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:617) ~[patched_1.17.1.jar:git-Paper-409]
        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:165) ~[patched_1.17.1.jar:git-Paper-409]
        at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:59) ~[patched_1.17.1.jar:git-Paper-409]
        at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:45) ~[patched_1.17.1.jar:git-Paper-409]
        at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:140) ~[patched_1.17.1.jar:git-Paper-409]
        at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:119) ~[patched_1.17.1.jar:git-Paper-409]
        at org.yaml.snakeyaml.composer.Composer.composeScalarNode(Composer.java:221) ~[patched_1.17.1.jar:git-Paper-409]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:191) ~[patched_1.17.1.jar:git-Paper-409]
        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:313) ~[patched_1.17.1.jar:git-Paper-409]
        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:304) ~[patched_1.17.1.jar:git-Paper-409]
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:288) ~[patched_1.17.1.jar:git-Paper-409]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:195) ~[patched_1.17.1.jar:git-Paper-409]
        at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:115) ~[patched_1.17.1.jar:git-Paper-409]
        at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:146) ~[patched_1.17.1.jar:git-Paper-409]
        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:151) ~[patched_1.17.1.jar:git-Paper-409]
        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:490) ~[patched_1.17.1.jar:git-Paper-409]
        at org.yaml.snakeyaml.Yaml.load(Yaml.java:416) ~[patched_1.17.1.jar:git-Paper-409]
        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57) ~[patched_1.17.1.jar:git-Paper-409]
        ... 24 more```

**Comment by Oribuin** [comment]
Can you try sending your tags.yml.
